### ISSUE TITLE
install faiss-cpu error in win10

### ISSUE THREAD

**Issue by ucasiggcas** [kyamagu/faiss-wheels#13]
hi,dear
when I install the faiss-cpu with
`pip install faiss-cpu`
then I got the error
```
Requirement already satisfied: numpy in d:\python\lib\site-packages (from faiss-cpu) (1.16.4)
Building wheels for collected packages: faiss-cpu
  Running setup.py bdist_wheel for faiss-cpu: started
  Running setup.py bdist_wheel for faiss-cpu: finished with status 'error'
  Complete output from command d:\python\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\xulm1\\AppData\\Local\\Temp\\pip-install-o6e2hn4b\\faiss-cpu\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\xulm1\AppData\Local\Temp\pip-wheel-8av9rpam --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\xulm1\AppData\Local\Temp\pip-install-o6e2hn4b\faiss-cpu\setup.py", line 107, in <module>
      ext_modules=[_swigfaiss]
    File "d:\python\lib\site-packages\setuptools\__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "d:\python\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "d:\python\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "d:\python\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\python\lib\site-packages\wheel\bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "d:\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\python\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "d:\python\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "d:\python\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "d:\python\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\xulm1\AppData\Local\Temp\pip-install-o6e2hn4b\faiss-cpu\setup.py", line 45, in run
      build_ext.run(self)
    File "d:\python\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\xulm1\AppData\Local\Temp\pip-install-o6e2hn4b\faiss-cpu\setup.py", line 50, in build_extensions
      self._remove_flag('-Wstrict-prototypes')
    File "C:\Users\xulm1\AppData\Local\Temp\pip-install-o6e2hn4b\faiss-cpu\setup.py", line 58, in _remove_flag
      compiler = self.compiler.compiler
  AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
```
  So could you pls help me?
thx

**Comment by kyamagu** [comment]
I believe faiss is not available on Windows. See https://github.com/facebookresearch/faiss/blob/master/INSTALL.md
