### ISSUE TITLE
windows 10 python39 error

### ISSUE THREAD

**Issue by jilieryuyi** [kyamagu/faiss-wheels#38]
import faiss
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\faiss\loader.py", line 34, in <module>
    from .swigfaiss import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\faiss\__init__.py", line 17, in <module>
    from .loader import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\faiss\loader.py", line 39, in <module>
    from .swigfaiss import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: 找不到指定的模块。

**Comment by espdev** [comment]
I have the same issue. 
I have looked through procmon, it seems `flang.dll` and `flangrti.dll` cannot be found.

![2021-05-14_16-48-40](https://user-images.githubusercontent.com/1299189/118279867-480fe600-b4d4-11eb-9500-ae7f70c4c386.png)

**Comment by espdev** [comment]
How to fix it manually:

1. Download the following archives:
https://anaconda.org/conda-forge/libflang/5.0.0/download/win-64/libflang-5.0.0-h6538335_20180525.tar.bz2
https://anaconda.org/conda-forge/openmp/7.0.0/download/win-64/openmp-7.0.0-h1ad3211_0.tar.bz2

2. Unpack and copy the following dll files to `site-packages\faiss` directory:
```
flang.dll
flangrti.dll
libomp.dll
ompstub.dll
```

I thing these missing dll files should be in whl.

**Comment by nithinreddyy** [comment]
Still throwing an error like 
`ImportError: DLL load failed: The specified module could not be found.`

**Comment by vyasn30** [comment]
Unpacking those dlls still doesn't solve the problem.
