### ISSUE TITLE
AttributeError: 'MSVCCompiler' object has no attribute 'compiler'

### ISSUE THREAD

**Issue by 18735549442** [kyamagu/faiss-wheels#52]
i install faiss-gpu by  both pip install faiss-gpu and conda install faiss-gpu.
however, results is below: 
  Using cached faiss-gpu-1.6.3.tar.gz (17 kB)
Requirement already satisfied: numpy in d:\anaconda3\envs\deep_sort_pytorch\lib\site-packages (from faiss-gpu) (1.18.2)
Building wheels for collected packages: faiss-gpu
  Building wheel for faiss-gpu (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\anaconda3\envs\deep_sort_pytorch\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ly\\AppData\\
Local\\Temp\\pip-install-ti6ccsjw\\faiss-gpu_4d5a94b24e0c468b855399b4ebb64aeb\\setup.py'"'"'; __file__='"'"'C:\\Users\\ly\\AppData\\Local\\Temp\\
pip-install-ti6ccsjw\\faiss-gpu_4d5a94b24e0c468b855399b4ebb64aeb\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().r
eplace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ly\AppData\Local\Temp\pip-
wheel-3x2ioo54'
       cwd: C:\Users\ly\AppData\Local\Temp\pip-install-ti6ccsjw\faiss-gpu_4d5a94b24e0c468b855399b4ebb64aeb\
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ly\AppData\Local\Temp\pip-install-ti6ccsjw\faiss-gpu_4d5a94b24e0c468b855399b4ebb64aeb\setup.py", line 111, in <module>
      ext_modules=[_swigfaiss]
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\ly\AppData\Local\Temp\pip-install-ti6ccsjw\faiss-gpu_4d5a94b24e0c468b855399b4ebb64aeb\setup.py", line 45, in run
      build_ext.run(self)
    File "D:\anaconda3\envs\deep_sort_pytorch\lib\distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\ly\AppData\Local\Temp\pip-install-ti6ccsjw\faiss-gpu_4d5a94b24e0c468b855399b4ebb64aeb\setup.py", line 50, in build_extensions
      self._remove_flag('-Wstrict-prototypes')
    File "C:\Users\ly\AppData\Local\Temp\pip-install-ti6ccsjw\faiss-gpu_4d5a94b24e0c468b855399b4ebb64aeb\setup.py", line 58, in _remove_flag
      compiler = self.compiler.compiler
  AttributeError: 'MSVCCompiler' object has no attribute 'compiler'

**Comment by kyamagu** [comment]
`faiss-gpu` is not supported on windows

**Comment by 18735549442** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已收到您的邮件。我将尽快给您回复。
